### ISSUE TITLE
what is the difference with original AIK paper?

### ISSUE THREAD

**Issue by xiaomingnio** [MengHao666/Minimal-Hand-pytorch#10]
In HybrIK paper, I see that 
![image](https://user-images.githubusercontent.com/25093691/121166566-c5383c00-c883-11eb-8f1e-b71a5d875dc3.png)

input has 3 parameter, but in your code 
![image](https://user-images.githubusercontent.com/25093691/121166813-f7e23480-c883-11eb-8f2d-37654fa7550e.png)
only 2.

what is the difference between those?

**Comment by MengHao666** [comment]
> In HybrIK paper, I see that
> ![image](https://user-images.githubusercontent.com/25093691/121166566-c5383c00-c883-11eb-8f1e-b71a5d875dc3.png)
> 
> input has 3 parameter, but in your code
> ![image](https://user-images.githubusercontent.com/25093691/121166813-f7e23480-c883-11eb-8f2d-37654fa7550e.png)
> only 2.
> 
> what is the difference between those?

Generally, I smplify their method. The last input parameter is the twist angle of human limb, and I overlook it as hand finger usually don't twist, should it be reasonable. You can find more details if u compare this code with their code.

All Best.
