### ISSUE TITLE
About solver in demo.py and op_pso.py

### ISSUE THREAD

**Issue by EEWenbinWu** [MengHao666/Minimal-Hand-pytorch#13]
Hi, I found that the solver = LM_solver... in **demo.py** do not be used, and the solver in **op_pso.py** is not define.
![image](https://user-images.githubusercontent.com/17973265/121211700-4822bc00-c8af-11eb-8b0d-1d1befeef09e.png)

**Comment by maitetsu** [comment]
I'm sorry about that. You're right, "solver = LM."_ "Solver..." is not used and can be deleted. I forgot to delete it when I published it. 

The solver in op_pso.py is used to test the accuracy of PSO algorithm for shape parameter estimation. If you run demo.py, you can delete three lines in the picture.
