### ISSUE TITLE
It can be helpful to consider Unity as frontend

### ISSUE THREAD

**Issue by vinnik-dmitry07** [MengHao666/Minimal-Hand-pytorch#2]
I have recently connected the original code to Unity through fast sockets. It looks easier and more powerful than open3d or matplotlib.

https://github.com/vinnik-dmitry07/minimal-hand

**Comment by MengHao666** [comment]
> I have recently connected the original code to Unity through fast sockets. It looks easier and more powerful than open3d or matplotlib.
> 
> https://github.com/vinnik-dmitry07/minimal-hand

It looks very cool sepecially for the real-time performance ! It is a regret that I have no idea about Unity.
And the idea for my reimplementation is to explore the train and evaluate process. And I didn't reimplement the original IKNet which is important for more precise prediction.

All the best.

**Comment by MengHao666** [comment]
> I have recently connected the original code to Unity through fast sockets. It looks easier and more powerful than open3d or matplotlib.
> 
> https://github.com/vinnik-dmitry07/minimal-hand

By the way, how do u track 2 hands at the same time? The original project dose not have such function.

**Comment by vinnik-dmitry07** [comment]
> > I have recently connected the original code to Unity through fast sockets. It looks easier and more powerful than open3d or matplotlib.
> > https://github.com/vinnik-dmitry07/minimal-hand
> 
> By the way, how do u track 2 hands at the same time? The original project dose not have such function.

np.flip =)
