### ISSUE TITLE
why is my result different from you ? the figure is not pose from hand  and generate error.

### ISSUE THREAD

**Issue by LingSmart** [MengHao666/Minimal-Hand-pytorch#20]
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by MengHao666** [comment]
I am sorry that I can't see the images that u want to upload0. Therefore , I cannot understand u at all.

**Comment by MengHao666** [comment]
I am sorry that I can't see the images that u want to upload. Therefore , I cannot understand u at all.

**Comment by LingSmart** [comment]
![image](https://user-images.githubusercontent.com/52542622/122340830-59d22680-cf75-11eb-9017-9c5dd26ef806.png)
![image](https://user-images.githubusercontent.com/52542622/122340902-71a9aa80-cf75-11eb-9843-b7c43c0a4e23.png)

**Comment by MengHao666** [comment]
Please check the conda virtual enviroment first. I have not met such error before.
