### ISSUE TITLE
why is my result different from you ? the figure is not pose from hand and generate error.

### ISSUE THREAD

**Issue by LingSmart** [MengHao666/Minimal-Hand-pytorch#21]
![image](https://user-images.githubusercontent.com/52542622/122341215-cfd68d80-cf75-11eb-8bee-3efa2e0df490.png)
![image](https://user-images.githubusercontent.com/52542622/122341314-ed0b5c00-cf75-11eb-9df5-44df3c42b75c.png)

**Comment by LingSmart** [comment]
![image](https://user-images.githubusercontent.com/52542622/122341492-1b893700-cf76-11eb-8e50-c67bbc5980c1.png)

**Comment by MengHao666** [comment]
You might check the version of open3D first. I didn't have such error before. Please deubg youself first. I am busy with another project now and may try to reproduce your error after several days.
