### ISSUE TITLE
Cannot plot 3d points

### ISSUE THREAD

**Issue by kishan1823** [MengHao666/Minimal-Hand-pytorch#23]
![image](https://user-images.githubusercontent.com/65106584/124465613-3d2a5100-ddb3-11eb-8c82-93d343141491.png)

Hi, i am not get the third window i.e 3d plot of keypoints of hand. Can you suggest any solution.

**Comment by MengHao666** [comment]
Please check the version of open3D. It might be solved by following https://github.com/MengHao666/Minimal-Hand-pytorch/blob/main/environment.yml

**Comment by kishan1823** [comment]
But the ploting of 3d points is using matplotlib https://github.com/MengHao666/Minimal-Hand-pytorch/blob/9030dcd80df4589ce34525d24808a6a0b67f04a3/demo.py#L48 and i had checked the version of matplolib. i have the same version even though i am not getting the plot.

**Comment by maitetsu** [comment]
Is there any warning or error in the terminal? Can you give me a screenshot of the terminal

**Comment by kishan1823** [comment]
There is no warning in the terminal
![image](https://user-images.githubusercontent.com/65106584/124479792-3fe17200-ddc4-11eb-9ea7-bbd0d4971559.png)

**Comment by maitetsu** [comment]
You can add " print(flited_joints + new_tran) " in line 99 of demo.py which is just before "filted_ax = vis.plot3d(flited_joints + new_tran, fliter_ax)". 
just like this
![2021-06-27 15-04-25 的屏幕截图](https://user-images.githubusercontent.com/53359928/124480277-acb33700-ddd9-11eb-8fa4-e2b78a965a49.png)

**Comment by maitetsu** [comment]
can you see any output in terminal

**Comment by kishan1823** [comment]
yes its printing a 2d array
![image](https://user-images.githubusercontent.com/65106584/124535273-799d9180-de33-11eb-8975-551039997334.png)

**Comment by kishan1823** [comment]
The issue resolved, after installing PyQt5 , Matplotlib dependecy
thank you
