### ISSUE TITLE
Environment file import failed

### ISSUE THREAD

**Issue by 14725836900** [MengHao666/Minimal-Hand-pytorch#25]
![Snipaste_2021-07-12_07-31-31](https://user-images.githubusercontent.com/59506524/125213044-9a5a6100-e2e3-11eb-9d52-4fe1d18cd6db.jpg)

**Comment by MengHao666** [comment]
we didn't meet such problems, please check the environment yourself.

**Comment by sidoodler** [comment]
@14725836900 Hi!
I am currently facing the same issue as you did. Could you tell me how exactly were you able to resolve it?
Thanks in advance!

**Comment by 14725836900** [comment]
@sidoodler 
Recreate the new environment

**Comment by 14725836900** [comment]
@sidoodler 
Add dependencies to the new environment according to the "environment.yml" file
