### ISSUE TITLE
where is "ckp_siknet_synth_41.pth.tar" in demo_dl.py

### ISSUE THREAD

**Issue by 18855727165** [MengHao666/Minimal-Hand-pytorch#26]
![FY`14~XX}SL% 626GG 088Y](https://user-images.githubusercontent.com/57395430/125462809-4898560f-080a-48a5-b2df-36cecb7fa085.png)

**Comment by MengHao666** [comment]
please refer to [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/main/ShapeNet.md)

**Comment by 14725836900** [comment]
“ckp_siknet_synth_41.pth.tar” triggers a chain error 
![ckp_tar](https://user-images.githubusercontent.com/59506524/126033814-b864fcdf-d65e-4d71-89b5-9a70a0f69b8b.jpg)
![issue1](https://user-images.githubusercontent.com/59506524/126033818-28d56c68-7621-4f8f-a1ec-ddc0eac43f27.jpg)
![issue2](https://user-images.githubusercontent.com/59506524/126033821-3bb3cb17-0877-4637-af39-749b36c4b385.jpg)

**Comment by MengHao666** [comment]
> “ckp_siknet_synth_41.pth.tar” triggers a chain error
> ![ckp_tar](https://user-images.githubusercontent.com/59506524/126033814-b864fcdf-d65e-4d71-89b5-9a70a0f69b8b.jpg)
> ![issue1](https://user-images.githubusercontent.com/59506524/126033818-28d56c68-7621-4f8f-a1ec-ddc0eac43f27.jpg)
> ![issue2](https://user-images.githubusercontent.com/59506524/126033821-3bb3cb17-0877-4637-af39-749b36c4b385.jpg)

@maitetsu
