### ISSUE TITLE
Unable to install some dependencies

### ISSUE THREAD

**Issue by sidoodler** [MengHao666/Minimal-Hand-pytorch#27]
Hi!
When I tried using the command 'conda env create --file=environment.yml', it threw me the following error:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - pcre==8.44=he6710b0_0
  - pixman==0.40.0=h7b6447c_0
  - tornado==6.1=py37h27cfd23_0
  - libopencv==3.4.2=hb342d67_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - qt==5.9.7=h5867ecd_1
  - libgfortran-ng==7.3.0=hdf63c60_0
  - freetype==2.10.4=h5ab3b9f_0
  - pandas==1.2.2=py37ha9443f7_0
  - sip==4.19.8=py37hf484d3e_0
  - libopus==1.3.1=h7b6447c_0
  - numpy-base==1.19.2=py37hfa32c7d_0
  - cffi==1.14.5=py37h261ae71_0
  - libxcb==1.14=h7b6447c_0
  - zstd==1.4.5=h9ceee32_0
  - readline==8.1=h27cfd23_0
  - libuv==1.40.0=h7b6447c_0
  - pyqt==5.9.2=py37h05f1152_2
  - harfbuzz==1.8.8=hffaf4a1_0
  - libuuid==1.0.3=h1bed415_2
  - gstreamer==1.14.0=h28cd5cc_2
  - torchvision==0.4.0=py37_cu100
  - libffi==3.3=he6710b0_2
  - ca-certificates==2021.1.19=h06a4308_0
  - lz4-c==1.9.3=h2531618_0
  - mkl_fft==1.3.0=py37h54f3939_0
  - expat==2.2.10=he6710b0_2
  - libtiff==4.1.0=h2733197_1
  - libgcc-ng==9.1.0=hdf63c60_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - xz==5.2.5=h7b6447c_0
  - icu==58.2=he6710b0_3
  - glib==2.67.4=h36276a3_1
  - setuptools==52.0.0=py37h06a4308_0
  - pillow==8.1.0=py37he98fc37_0
  - termcolor==1.1.0=py37h06a4308_1
  - zlib==1.2.11=h7b6447c_3
  - libpng==1.6.37=hbc83047_0
  - python==3.7.10=hdb3f193_0
  - mkl==2020.2=256
  - scipy==1.6.1=py37h91f5cce_0
  - kiwisolver==1.3.1=py37h2531618_0
  - jasper==2.0.14=h07fcdf6_1
  - ncurses==6.2=he6710b0_1
  - mkl-service==2.3.0=py37he8ac12f_0
  - numpy==1.19.2=py37h54aff64_0
  - libxml2==2.9.10=hb55368b_3
  - pytorch==1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - hdf5==1.10.2=hba1933b_1
  - py-opencv==3.4.2=py37hb342d67_1
  - ffmpeg==4.0=hcdf2ecd_0
  - pip==21.0.1=py37h06a4308_0
  - lcms2==2.11=h396b838_0
  - intel-openmp==2020.2=254
  - libvpx==1.7.0=h439df22_0
  - libglu==9.0.0=hf484d3e_1
  - matplotlib-base==3.3.4=py37h62a2d02_0
  - bzip2==1.0.8=h7b6447c_0
  - dbus==1.13.18=hb2f20db_0
  - mkl_random==1.1.1=py37h0573a6f_0
  - openssl==1.1.1j=h27cfd23_0
  - certifi==2020.12.5=py37h06a4308_0
  - fontconfig==2.13.1=h6c09931_0
  - graphite2==1.3.14=h23475e2_0
  - cudatoolkit==10.0.130=0
  - ninja==1.10.2=py37hff7bd54_0
  - tk==8.6.10=hbc83047_0
  - matplotlib==3.3.4=py37h06a4308_0
  - libedit==3.1.20191231=h14c3975_1
  - cairo==1.14.12=h8948797_3
  - freeglut==3.0.0=hf484d3e_5
  - sqlite==3.33.0=h62c20be_0
  - gst-plugins-base==1.14.0=h8213a91_2
  - jpeg==9b=h024ee3a_2

Do I need to install all these dependencies individually or should the above command have worked as it is?
Please help me out as installing them individually is also not working with pip. Further, let me know if I need to use some package manager other than pip for individual installation.

Thanks in advance!

**Comment by MengHao666** [comment]
Sorry, I didn't met such problem before and am busy with another project now. You may ask the guy with 
 similar issues see [here](https://github.com/MengHao666/Minimal-Hand-pytorch/issues/25). 
Anyway , u might install these independices yourself by seeing which packages are missing when u run the code.

**Comment by sidoodler** [comment]
@MengHao666 Thank you so much for the prompt reply!
I'll check it out with the other guy. Thanks again.

**Comment by zhaoliyue** [comment]
@sidoodler I got the same issue and wonder how did you fix it?

**Comment by sidoodler** [comment]
@zhaoliyue actually I couldn't fix it. When I checked with the other guy, he told me that I needed to install all the dependencies manually via pip or conda. As it was a lot of work, I gave it up and looked for alternative repos.

**Comment by MengHao666** [comment]
@zhaoliyue @sidoodler It should not be a problem as many pepole have tried it. I am so sorry I am busy with another project. I will check it once I have time.

**Comment by MengHao666** [comment]
u may refer to  [here](https://github.com/MengHao666/Minimal-Hand-pytorch/issues/29#issue-976328196)
