### ISSUE TITLE
RuntimeError: Tensor for 'out' is on CPU, Tensor for argument #1 'self' is on CPU, but expected them to be on GPU (while checking arguments for addmm) [ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-n4ekh6o5\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

### ISSUE THREAD

**Issue by Alvin-guodong** [MengHao666/Minimal-Hand-pytorch#28]
Hi, there
I've been trying to run the code but failed, this is the error I get.
el start
load model finished
start opencv
opencv finished
Traceback (most recent call last):
  File "C:/Users/1/PycharmProjects/Minimal-Hand-pytorch-main/demo.py", line 55, in <module>
    hand_verts, j3d_recon = mano(pose0, shape.float())
  File "E:\Users\1\anaconda3\envs\yolo\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\1\PycharmProjects\Minimal-Hand-pytorch-main\manopth\manolayer.py", line 187, in forward
    th_v_posed = th_v_shaped + torch.matmul(
RuntimeError: Tensor for 'out' is on CPU, Tensor for argument #1 'self' is on CPU, but expected them to be on GPU (while checking arguments for addmm)
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-n4ekh6o5\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

Any ideas as to how to fix this? Thanks in advance

**Comment by MengHao666** [comment]
@Alvin-guodong  Try to run `print(torch.cuda.is_available())`

**Comment by canghaiyunfan** [comment]
I also meet this error, torch.cuda.is_available() is True
`File "/home/zy/code/Minimal-Hand-pytorch/demo_dl.py", line 66, in <module>
    hand_verts, j3d_recon = mano(pose0, shape.float())
  File "/home/zy/miniconda3/envs/zy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zy/miniconda3/envs/zy/lib/python3.8/site-packages/manopth/manolayer.py", line 187, in forward
    th_v_posed = th_v_shaped + torch.matmul(
RuntimeError: Tensor for 'out' is on CPU, Tensor for argument #1 'self' is on CPU, but expected them to be on GPU (while checking arguments for addmm)`

as the above error states describes, in manolayer.py `th_v_posed = th_v_shaped + torch.matmul(self.th_posedirs, th_pose_map.transpose(0, 1)).permute(2, 0, 1)`. the  th_v_shaped and self.th_posedirs's device is cpu, but the th_pose_map's device is cuda.

**Comment by MengHao666** [comment]
Please refer to [here](https://github.com/MengHao666/Minimal-Hand-pytorch/issues/28#issuecomment-1132733611)
