### ISSUE TITLE
Redundant requirement in environment.yml

### ISSUE THREAD

**Issue by Omri-CG** [MengHao666/Minimal-Hand-pytorch#29]
Hi,

Thanks for this great implementation! 

I believe you should drop the requirement for `manopth==0.0.1` from your [`environment.yml`](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/main/environment.yml#L98) file, as it does not exists in PyPI. Just leave the requirement to install it from its Github project.

**Comment by MengHao666** [comment]
> Hi,
> 
> Thanks for this great implementation!
> 
> I believe you should drop the requirement for `manopth==0.0.1` from your [`environment.yml`](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/main/environment.yml#L98) file, as it does not exists in PyPI. Just leave the requirement to install it from its Github project.

thank u so much, I will check it when I have time.
