### ISSUE TITLE
what is the ID2ROT and the purpose of using it?

### ISSUE THREAD

**Issue by wangzheallen** [MengHao666/Minimal-Hand-pytorch#30]
as in 
https://github.com/MengHao666/Minimal-Hand-pytorch/blob/947f29a505c2b3bdf3e36b43121b3c692de93fcc/utils/AIK.py#L102
and 
https://github.com/MengHao666/Minimal-Hand-pytorch/blob/947f29a505c2b3bdf3e36b43121b3c692de93fcc/config.py#L126

**Comment by MengHao666** [comment]
@wangzheallen  hi, ID2ROT should denote the mapping between rotation matrixs computed in last step and joint ids.

**Comment by wangzheallen** [comment]
@MengHao666  Thanks! Do you define the ids or where do you get this mappings?

**Comment by MengHao666** [comment]
hi, the id is following https://github.com/MengHao666/Minimal-Hand-pytorch/blob/947f29a505c2b3bdf3e36b43121b3c692de93fcc/config.py#L52.
,and it is just the order of 21 joints. Using the above mapping could define the mapping between  rotation matrixs of manopth layer and the joint ids following such order. Hope I could explain it clearly.
