### ISSUE TITLE
about the shape estimation

### ISSUE THREAD

**Issue by zjhthu** [MengHao666/Minimal-Hand-pytorch#31]
[An issue ](https://github.com/CalciferZh/minimal-hand/issues/89)from the official repo.
------------------------------
Hi, I am wondering, once the pose and shape parameters are estimated, the absolute scale of the hand model will also be recovered. Does it mean that the network estimates an absolute-scale hand model from a single image?
I am a new hand in this area, is the MANO model scale-independent?

**Comment by MengHao666** [comment]
hi, it should only give a reltaive cooridinates considering the only RGB input. So in my re-implementation, the 21 3D joint location prediction is root-relative and scale-invariant, u can see [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/c078433136b20c1e4fb3f353254edd409ea65f1b/datasets/handataset.py#L240) and [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/c078433136b20c1e4fb3f353254edd409ea65f1b/datasets/handataset.py#L241) for details.

However, the mano model could represent hand in an abosolute sacle and global cooridiante. It also has its own  unit. In my re-implementation and offical paper, we try to fit an abosolute mano model with the  root-relative and scale-invariant prediction. For more details, u should read carefully my code and read the paper.

**Comment by zjhthu** [comment]
Hi, the problem is that both you and the official code try to fit an absolute scale Mano model from only scale-invariant predictions. This can be possible if the Mano model is scale-invariant. Do you mean the final hand model is a scaled-version Mano model?
If the Mano model has absolute scale, then the camera center can be inferred from PnP, and the root depth can also be obtained.

**Comment by MengHao666** [comment]
> Hi, the problem is that both you and the official code try to fit an absolute scale Mano model from only scale-invariant predictions. This can be possible if the Mano model is scale-invariant. Do you mean the final hand model is a scaled-version Mano model?
> If the Mano model has absolute scale, then the camera center can be inferred from PnP, and the root depth can also obtained.

Sorry, I might not understand u fully. But frankly speaking, the fitting procedure in my or offical code might be much simpler than what you think about. We just try to fit the absolute mano model with the relative 3d joint locations. Once we feed the mano model with its pose and shape parameters, we get its output, i.e., 21 joint 3d locations and 778 vertex 3d locations. Then , we process its to be root-relative and scale-invaraiant, and compare it with former relative 3d joint locations.

**Comment by zjhthu** [comment]
I mean, it should be not possible to get an absolute scale output from just relative-scale input. No matter this process is a network or an optimization solver.

**Comment by MengHao666** [comment]
> I mean, it should be not possible to get an absolute scale output from just relative-scale input. No matter this process is a network or an optimization solver.

Sure.

**Comment by zjhthu** [comment]
So I am still confusing how could it be possible to infer Mano shape parameter from relative-scale input.

**Comment by maitetsu** [comment]
Mano has three sets of parameters,

1. Rotation parameters. This is independent of size and can be inferred.

2. Shape parameters. The code we implemented just gets a shape parameter with the smallest error in the relative relationship of the input hand. Here is only a relative relationship and no absolute length.

3. Translation parameters. There are no estimates in our code implementation.

The whole estimation process does not use absolute length information.
