### ISSUE TITLE
why only fives finger tips are used in the evaluation of EO and DO dataset

### ISSUE THREAD

**Issue by zjhthu** [MengHao666/Minimal-Hand-pytorch#33]
I find only five fingertips are used in these two datasets. Is this a common practice? 
This original paper said they use these five joints for global scale and translation alignment, but did not mention that they just use these five joints for evaluation. Why not evaluate all 21 joints after alignment?

**Comment by MengHao666** [comment]
> I find only five fingertips are used in these two datasets. Is this a common practice?
> This original paper said they use these five joints for global scale and translation alignment, but did not mention that they just use these five joints for evaluation. Why not evaluate all 21 joints after alignment?

Hi, DO and ED(EO) only have annotations for 5 fingertips. And such alignment method just followed the original paper.

**Comment by zjhthu** [comment]
thanks
