### ISSUE TITLE
"ckp_siknet_synth_41.pth.tar"have a error

### ISSUE THREAD

**Issue by LingSmart** [MengHao666/Minimal-Hand-pytorch#34]
there is a error,how to solve ?

RuntimeError: G:/Minimal-Hand-pytorch/my_results/checkpoints/ckp_siknet_synth_41.pth.tar is a zip archive (did you mean to use torch.jit.load()?)

![图片](https://user-images.githubusercontent.com/52542622/134811221-c130b473-f340-4a03-8d31-f5e54f08cd2e.png)

**Comment by MengHao666** [comment]
Is your pytorch version consistent with mine?

**Comment by LingSmart** [comment]
my torch is 1.2.0 .it is same to you

**Comment by maitetsu** [comment]
I'm sorry. It's my fault. I train ShapeNet and test all model in pytorch=1.8 . This leads to incompatibility. I will update the model

**Comment by maitetsu** [comment]
I have updated the ckp_siknet_synth_41.pth.tar of Google drive. The new model can be load by torch=1.2. You can download it by origin link.

**Comment by LingSmart** [comment]
ok 。I have another question,why do you choose this model(ckp_siknet_synth_41.pth.tar )? because it is good for shape estimate in all model ?

**Comment by maitetsu** [comment]
I didn't choose shapenet very carefully. I just looked at the estimation effect of the real-time demo.

**Comment by LingSmart** [comment]
ok ,i know.

**Comment by LingSmart** [comment]
there is another question .the file (rhd_pso.npy) is not find.I didn't find any pattern files,for example do_pso.npy,eo_pso.npy.stb_pso.npy 。

**Comment by LingSmart** [comment]
i run it  .but just get the file(do_shapes.npy).

**Comment by maitetsu** [comment]
you can rename these files. just change do_shapes.npy to do_pso.npy.  do_pso.npy means  the shape parameters estimated by PSO on DO dateset.

**Comment by sanyong-sys** [comment]
There are only four detnet pths in the my_results folder

**Comment by MengHao666** [comment]
> There are only four detnet pths in the my_results folder

you would find it in Readme.md
