### ISSUE TITLE
Environment installation fails

### ISSUE THREAD

**Issue by Haydnspass** [MengHao666/Minimal-Hand-pytorch#36]
Hey,
I tried installing the environment, unfortunately, it fails either due to manopth or the MANO models.
Can you help me out? Anything I need to specify differently?

```
(minimal-hand-torch) muellelu@e130-pc25:~/git/minimal-hand-pytorch$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from manopth import manolayer
  File "/home/AD/muellelu/xconda3/envs/minimal-hand-torch/lib/python3.7/site-packages/manopth/manolayer.py", line 7, in <module>
    from mano.webuser.smpl_handpca_wrapper_HAND_only import ready_arguments
  File "/home/AD/muellelu/git/minimal-hand-pytorch/mano/webuser/smpl_handpca_wrapper_HAND_only.py", line 137
    print 'FINITO'
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('FINITO')?
(minimal-hand-torch) muellelu@e130-pc25:~/git/minimal-hand-pytorch$ 
```

**Comment by MengHao666** [comment]
Hi, would you check [here](https://github.com/MengHao666/Minimal-Hand-pytorch/issues/29#issue-976328196) to have a try?

**Comment by Haydnspass** [comment]
@MengHao666 thanks for the fast response.
Unfortunately, that does not help. It seems that the python files of the mano model use python version 2.* (`print "something"` instead of `print("something")`. That's quite strange

**Comment by maitetsu** [comment]
The official code of mano is written in python2. Manopth migrates the official code of mano to python3. You need to replace the official code of mano with the code of manopth. I think you maybe replace the code of manopth with the official code of mano, this can't run in python3.

**Comment by Haydnspass** [comment]
I think in essence I just had to delete all *.py files that are automatically in the .zip of the MANO models. Without, I got further

**Comment by maitetsu** [comment]
You can try your method. But, I'm not sure whether manopth completely migrates all mano code to Python 3. Maybe some code can also run in Python 3, so they are not migrated. 
My method is to choose not to overwrite manopth when decompressing the mano model.

**Comment by Haydnspass** [comment]
@maitetsu so you manually copy/install manopth? I guess this i not reflected in the instructions?
Currently manopth is installed automatically via the environment file.

**Comment by maitetsu** [comment]
yes. I manually install manopth. More details you can see https://github.com/hassony2/manopth#installation
