### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'out_testset/rhd_pso.npy' 

### ISSUE THREAD

**Issue by LingSmart** [MengHao666/Minimal-Hand-pytorch#37]
the file (rhd_pso.npy) is not find.I didn't find any pattern files,for example do_pso.npy,eo_pso.npy.stb_pso.npy 。
![图片](https://user-images.githubusercontent.com/52542622/135233761-cce1d63c-80d5-4983-b5a8-5349d038feb1.png)

**Comment by maitetsu** [comment]
This file is the result of PSO estimating shape parameters, which can be obtained by running op_pso.py . So, I don't upload it. 
Just run   "  python op_pso.py ". You can get these file.
