### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'mano/models\\MANO_RIGHT.pkl'

### ISSUE THREAD

**Issue by LingSmart** [MengHao666/Minimal-Hand-pytorch#39]
i have the file in this directory ,but still have this error,how can i solve it ?
![图片](https://user-images.githubusercontent.com/52542622/135720640-b17b2388-0ffa-4883-8dd1-8bec8adb5f49.png)

**Comment by MengHao666** [comment]
please run. ‘print(os.path.exists(your_path))’
to check if your path exists.

**Comment by LingSmart** [comment]
this run ?
![图片](https://user-images.githubusercontent.com/52542622/135721204-fa70cc62-d4b7-4dbb-a10b-23089224508c.png)
but i have this file in my directory.look :
![图片](https://user-images.githubusercontent.com/52542622/135721259-0b8ad2cc-828f-4891-aee8-96b2973471cb.png)

**Comment by MengHao666** [comment]
It looks like the path doesn’t exist at all.please check the path of the file again, should it be noted that the difference between Window and Ubuntu, i.e.,”\\“ and “/“.

**Comment by LingSmart** [comment]
ok，I changed the path to an absolute path, so it should be no problem.

**Comment by LingSmart** [comment]
thank your answer,this question solved. but another question happen. i dont change this code.i dont know why this is .
![图片](https://user-images.githubusercontent.com/52542622/135738311-0a3888c8-980a-4069-b13e-be244384cb4b.png)

**Comment by MengHao666** [comment]
This is just code for debug and is not important.
