### ISSUE TITLE
a bug when inferring xyz

### ISSUE THREAD

**Issue by elephanting** [MengHao666/Minimal-Hand-pytorch#4]
Hi, thanks for your great work.
I think there is a small bug at

https://github.com/MengHao666/Minimal-Hand-pytorch/blob/ab9768c21a31a8f31ef7d96dc42ab434c0f422e8/model/detnet/detnet.py#L136

If the batch size is equal to 1, the first dimension will also be squeezed.
I think it should be squeeze(2) instead of squeeze().
Thank you.

**Comment by MengHao666** [comment]
Hi，
Thanks for pointing out this bug. I didn't consider this bug before ,as the batchsize here is nealry more than 1 all the time, either in training or evaluation.
I have fixed it now, see   [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/947f29a505c2b3bdf3e36b43121b3c692de93fcc/model/detnet/detnet.py#L136) 

All Best,
Hao Meng
