### ISSUE TITLE
"resnet_helper.py" this file have a error

### ISSUE THREAD

**Issue by LingSmart** [MengHao666/Minimal-Hand-pytorch#40]
"resnet_helper.py" this file have a missing for a file ,see in the following :
![图片](https://user-images.githubusercontent.com/52542622/135754751-96e0eb31-9b54-41a8-93f8-fa075c33fcfd.png)

**Comment by MengHao666** [comment]
I'm sorry that line of code is wrote for debug only, so you could neglect it or correct with the inputs you designed.
