### ISSUE TITLE
does analytical IK improves the performance over IKNet

### ISSUE THREAD

**Issue by wangzheallen** [MengHao666/Minimal-Hand-pytorch#42]
based on your experiments log, does analytical IK improves the performance over IKNet?

**Comment by MengHao666** [comment]
Hi, thanks for interest. It would be  a solution considering the train data of IKNet is not open source. The analytical IK is a sub optimal stronly depending on the previous predicted hand pose.

Anyway, as we could see from the chart of experiments in Readme.md, the analytical IK provide competitive or even superior results compared with IKNet. Of course, it is a coarse comparision as the codes of offical projects  are not open source.

**Comment by wangzheallen** [comment]
Thanks for the quick response!
Is the chart below you mentioned? if so, may  I ask which is your implementation of  IKNet
and which one is the analytical IK in the chart?
which two parts are you comparing in the chart?

Dataset | DetNet(paper) | DetNet(*) | DetNet+IKNet(paper) | DetNet+LM+AIK(*) | DetNet+PSO+AIK(*) | DetNet+DL+AIK(*)
-- | -- | -- | -- | -- | -- | --
RHD | - | 0.9339 | 0.856 | 0.9301 | 0.9310 | 0.9272
STB | 0.891 | 0.8744 | 0.898 | 0.8647 | 0.8671 | 0.8624
DO | 0.923 | 0.9378 | 0.948 | 0.9392 | 0.9342 | 0.9400
EO | 0.804 | 0.9270 | 0.811 | 0.9288 | 0.9277 | 0.9365

**Comment by MengHao666** [comment]
> ne is the analytical IK in the chart?

Sorry for late response. This is the chart that I mentioned. We didn't reproduce IKNet but replace it with AIK, a purely mathematical method. In the chart, we want to see how different shape estimation methods perform and how AIK perform.
