### ISSUE TITLE
what is the code  result ?

### ISSUE THREAD

**Issue by LingSmart** [MengHao666/Minimal-Hand-pytorch#43]
Hello,the final result of your code  is  a model of OBJ file (which can be imported into 3D Max) or is it just a hand of 3d image displayed in the picture, such as looking at the picture representation:
![图片](https://user-images.githubusercontent.com/52542622/141416419-8726bccc-57ed-41a3-9aca-b9c1f62c3d63.png)
 or obj file like this:
![图片](https://user-images.githubusercontent.com/52542622/141416612-05402434-43fa-434e-a236-f7509cc1eee4.png)

**Comment by MengHao666** [comment]
Hi, it seems like the result is not very promising in your "the picture representation", and you might try to enlarge the weight of shape parameter regularizer.

And , our code adapt original manopth code, so we could display the 3D hand mesh with open3d. Please be so kind to check our code caresully in [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/main/demo_dl.py)

**Comment by LingSmart** [comment]
i have run this code,this result is just a 3d model in a picture



At 2021-11-12 13:59:14, "Hao Meng" ***@***.***> wrote:

Hi, it seems like the result is not very promising in your "the picture representation", and you might try to enlarge the weight of shape parameter regularizer.

And , our code adapt original manopth code, so we could display the 3D hand mesh with open3d. Please be so kind to check our code caresully in here

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LingSmart** [comment]
i have run this code,this result is just a 3d model in a picture ,like tis ,this is the same as your ?
![图片](https://user-images.githubusercontent.com/52542622/141426767-a92b9825-b44d-45d1-adca-fdde97335d6b.png)

**Comment by LingSmart** [comment]
“we could display the 3D hand mesh with open3d” your mean is just see this mesh  effect,dont output a model for import the 3d software,such as 3d max 、maya ?

**Comment by MengHao666** [comment]
Actually, it would be very easy to save the hand mesh as the faces (check [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/c078433136b20c1e4fb3f353254edd409ea65f1b/demo_dl.py#L65)) and verts (check [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/c078433136b20c1e4fb3f353254edd409ea65f1b/demo_dl.py#L64)) are available.

**Comment by LingSmart** [comment]
I dont understand what your mean how to do it ？



At 2021-11-12 17:10:52, "Hao Meng" ***@***.***> wrote:

e

Actually, it would be very easy to save the hand mesh as the faces (check here) and verts (check here) are available.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MengHao666** [comment]
If you are famliar with computer graphics, such operation could be very easy to implement.
[Here](https://github.com/facebookresearch/InterHand2.6M/blob/2b8061d2c8e762aa6fcb8e6f5d18f8a9e83bfd0c/tool/MANO_render/render.py#L15) is an example to save hand mesh in the format of '.obj'.

**Comment by LingSmart** [comment]
I see it .sorry,I just learn to CG.i need learn to more



At 2021-11-12 17:42:58, "Hao Meng" ***@***.***> wrote:

If you are famliar with computer graphics, such operation could be very easy to implement.
Here is an example to save hand mesh in the format of '.obj'.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MengHao666** [comment]
> I see it .sorry,I just learn to CG.i need learn to more At 2021-11-12 17:42:58, "Hao Meng" ***@***.***> wrote: If you are famliar with computer graphics, such operation could be very easy to implement. Here is an example to save hand mesh in the format of '.obj'. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Never minds. I am also a beginner in computer graphics.
