### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'out_testset/rhd_dl.npy'

### ISSUE THREAD

**Issue by 18855727165** [MengHao666/Minimal-Hand-pytorch#44]
![~KJU {11LBI`CZC{K8IW`QN](https://user-images.githubusercontent.com/57395430/143396364-77500f9a-f2b6-4ec7-8911-bb82d1de79af.png)

**Comment by MengHao666** [comment]
Hi, I thought I have provided the link this file, please read the Readme.md carefully.

**Comment by 18855727165** [comment]
can i have a exact location？

**Comment by HanXiaoyou** [comment]
I think it need to be change to `_shapes` in [aik_pose.py](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/c078433136b20c1e4fb3f353254edd409ea65f1b/aik_pose.py#L76). Beacuse in fold `my_results\out_testset`  the files are `*_shapes.npy`.

**Comment by MengHao666** [comment]
> 

I am sorry that I couldn't remember very clearly. Please have a try and check the outcome.
