### ISSUE TITLE
error about demo.py

### ISSUE THREAD

**Issue by willcococv** [MengHao666/Minimal-Hand-pytorch#46]
Sorry, this error occurred when I was running demo.py. Has this file been deleted? Thank you ！
![图片](https://user-images.githubusercontent.com/81727800/143969841-af3e84de-0d8f-4033-91e3-738b0a29ca9a.png)

**Comment by MengHao666** [comment]
please refer to [here](https://github.com/hassony2/manopth). And we have modified rotproj.py in our repo.

**Comment by willcococv** [comment]
Thank you very much for your answer

> 请参考 [这里 ](https://github.com/hassony2/manopth)。 我们在我们的 repo 中修改了 rotproj.py。
