### ISSUE TITLE
TypeError: update_geometry(): incompatible function arguments.

### ISSUE THREAD

**Issue by willcococv** [MengHao666/Minimal-Hand-pytorch#47]
Hello, I encountered this problem when running the demo. I have upgraded open3d to 0.9, but I still can't solve it. Do you have a better way？
![图片](https://user-images.githubusercontent.com/81727800/144007124-dca9f9b9-721b-4a0d-8efb-468a9a2ac396.png)

**Comment by MengHao666** [comment]
@maitetsu

**Comment by willcococv** [comment]
> @maitetsu

Thank you for your answer. When I comment out the code displaying mesh and continue to run the program, there is a problem. When my hand does not appear in the camera, messy key points will be generated. When my hand appears in the camera, very inaccurate and jittery key points will appear
![图片](https://user-images.githubusercontent.com/81727800/144339974-618a5751-bc5f-40d6-ae3d-6e994057f59b.png)
![图片](https://user-images.githubusercontent.com/81727800/144340222-767171a7-9e8c-4b24-8818-173ae3f2793f.png)

**Comment by MengHao666** [comment]
hi, in our train setting, hand is nearly in the center of the image, and the hand scale displayed is about half size of image. The other possible reason might be that we have a simple smooth filter to make predictions smooth in temporal space.

**Comment by maitetsu** [comment]
About this error, I haven't encountered. You can try other open3d version.
