### ISSUE TITLE
trained model result is not good 

### ISSUE THREAD

**Issue by Gzzgz** [MengHao666/Minimal-Hand-pytorch#5]
Hi,
 I trained model following the instruction completely. But I got the result is that:

![图片](https://user-images.githubusercontent.com/15968092/116176708-3218cc00-a745-11eb-8cab-afaa14cfe65e.png)

another your model result:
![图片](https://user-images.githubusercontent.com/15968092/116177010-abb0ba00-a745-11eb-80ad-b36f70ba7578.png)

**Comment by MengHao666** [comment]
please refer to the data preprocessing, see [scale_factor](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/947f29a505c2b3bdf3e36b43121b3c692de93fcc/utils/handutils.py#L230)

Here, the hand is in center location of image and the scale in 2D is about 1/2 of the image  when scale_factor=2.0. 
For result you want, u could follow my settings or re-train the network after  adjust the preprocess params or use much bigger augmentation value, see [augmentation](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/947f29a505c2b3bdf3e36b43121b3c692de93fcc/datasets/handataset.py#L160)

**Comment by MengHao666** [comment]
@Gzzgz 
Maybe it is also realted to the limited trainset. The offical project didn't do well either in some situations. see [offical bad result](https://github.com/CalciferZh/minimal-hand/issues/25)

**Comment by Gzzgz** [comment]
I don't think so. This is a pro.

**Comment by MengHao666** [comment]
> I don't think so. This is a pro.

So what do you make of all this？

**Comment by lsl136** [comment]
> Hi, I trained model following the instruction completely. But I got the result is that:
> 
> ![图片](https://user-images.githubusercontent.com/15968092/116176708-3218cc00-a745-11eb-8cab-afaa14cfe65e.png)
> 
> another your model result: ![图片](https://user-images.githubusercontent.com/15968092/116177010-abb0ba00-a745-11eb-80ad-b36f70ba7578.png)

Hello, I met the same problem as you, did you solve this problem? If it did, how to solve it?
