### ISSUE TITLE
about train shape net.

### ISSUE THREAD

**Issue by llpspark** [MengHao666/Minimal-Hand-pytorch#51]
hi, great work for 3D hand ,and I reproduce the shape net but the shape  L2 regularizer loss alwary go up, whether it is normal？

![屏幕快照 2021-12-10 上午11 54 40](https://user-images.githubusercontent.com/20918669/145540430-42a5eb65-82e3-4f22-93c1-e773b14f1113.png)

**Comment by MengHao666** [comment]
@maitetsu

**Comment by llpspark** [comment]
@maitetsu hello , thank u for ur commit,  do u have some idea about this problem?

**Comment by MengHao666** [comment]
> @maitetsu hello , thank u for ur commit, do u have some idea about this problem?

hi, the shapenet is for shape estimation. so the weight of shape L2 regularizer should be set considering the trade-off  between accurate bone length and  shape L2 regularizer loss, u might want to try to change the weight of shape L2 regularizer if u like. The shape L2 regularizer is set to make predicted hand shape close to mean hand shape (0).

Hope I have explained it well. For more deatails , please ask @maitetsu .

**Comment by llpspark** [comment]
@MengHao666 thanks for ur reply. I think it is reasonable，and I will try some weight to check this problem.
