### ISSUE TITLE
about show result.

### ISSUE THREAD

**Issue by llpspark** [MengHao666/Minimal-Hand-pytorch#53]
Hello , I have install open3d properly , but when I run the demo,  can't show the result, just white board(both demo.py and demo_dl.py), I wonder whether some result error?
<img width="1421" alt="屏幕快照 2021-12-13 下午1 56 54" src="https://user-images.githubusercontent.com/20918669/145762804-5c5dbb9b-d176-47eb-98e2-1ab12e88571d.png">

**Comment by MengHao666** [comment]
@maitetsu

**Comment by llpspark** [comment]
@maitetsu hello, do u have some idea about this problem?  Thx. I have check the open3d is normal with plot point cloud .

**Comment by maitetsu** [comment]
If I encounter this problem. 
1. First I will confirm whether hand_verts  is correct.  
2. Then, I will try to run the code to the first time poll_events() called , try to zoom and pan the window to find the hand model. If I can see it, maybe there are some errors in viewer.view_control. Then I will to change  viewer.view_control

**Comment by llpspark** [comment]
@maitetsu  yea, I have check the hand_verts is correct. I think maybe the "    viewer.update_geometry(mesh) or  viewer.poll_events()" have some thing wrong, because I create viewer object in every frame it can be show the mesh. but the reason of detail haven' t know.
