### ISSUE TITLE
about projecting the mesh to image.

### ISSUE THREAD

**Issue by llpspark** [MengHao666/Minimal-Hand-pytorch#54]
hello, do u have some idea about projecting the output's mesh to original image approximatively? Of course  assume no camera intrict parameters. I think the accuracy of mesh can be judged more accurately when mesh is projected into the image.just like the paper show:
<img width="137" alt="屏幕快照 2021-12-14 下午3 17 51" src="https://user-images.githubusercontent.com/20918669/145951056-1e6ef5f1-32f7-474e-8e8f-7c72c62432d3.png">

**Comment by MengHao666** [comment]
you might refer to original paper or project. They use the  camera intrict parameters , the predicted 2D hand pose , the relative 3D hand pose and possible ground truth reference bone length to get a global hand mesh and then projected it into image.
