### ISSUE TITLE
about kpt order convertion in different dataset(convert to SNAP's order)

### ISSUE THREAD

**Issue by llpspark** [MengHao666/Minimal-Hand-pytorch#55]
hi, when I check the train code. I found that the kpt order convertion in different dataset(convert to SNAP's order) maybe has some   bug. just like STB to SNAP order, the implement is:
![屏幕快照 2021-12-22 上午10 53 33](https://user-images.githubusercontent.com/20918669/147027523-69a373cc-0535-4980-9eed-9c780b400f3b.png)
![屏幕快照 2021-12-22 上午10 53 53](https://user-images.githubusercontent.com/20918669/147027559-66af580f-d4d7-47c8-b3cc-7aaa143c7aed.png)
I think it will not convert properly. where should like this?
![屏幕快照 2021-12-22 上午10 55 17](https://user-images.githubusercontent.com/20918669/147027710-167ae8e6-6cfa-4fc9-92bd-bcafdfaad939.png)
![屏幕快照 2021-12-22 上午10 57 02](https://user-images.githubusercontent.com/20918669/147027883-9356ebc9-6c37-4f0a-ac77-3b2088c8465f.png)

**Comment by MengHao666** [comment]
this operation could convert  different orders from different dataset into same order.
