### ISSUE TITLE
Runtime cuda error.

### ISSUE THREAD

**Issue by ykk648** [MengHao666/Minimal-Hand-pytorch#56]
File ".../python3.7/site-packages/manopth-0.0.1-py3.7.egg/manopth/manolayer.py", line 182, in forward
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'mat2'

**Comment by MengHao666** [comment]
please check this issue [here](https://github.com/MengHao666/Minimal-Hand-pytorch/issues/11)
