### ISSUE TITLE
parameter name error in readme.md

### ISSUE THREAD

**Issue by HanXiaoyou** [MengHao666/Minimal-Hand-pytorch#57]
Thanks for your excellent project! And I find a tiny error in [readme.md](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/main/README.md#detnet-training-and-evaluation-curve). It should be `python plot.py --out_path my_results/out_loss_auc`  rather than `python plot.py --path my_results/out_loss_auc`.

**Comment by MengHao666** [comment]
thanks a lot
