### ISSUE TITLE
你好，请问通过反向动力学得到的16个rotation_matrix的坐标系是怎么样的，我在应用到smpl的模型时发现不是很对。

### ISSUE THREAD

**Issue by sunhaha123** [MengHao666/Minimal-Hand-pytorch#58]
![微信截图_20220304155630](https://user-images.githubusercontent.com/27773261/156722879-9039dafa-2c26-48b1-8997-e22a387d6248.png)
![image](https://user-images.githubusercontent.com/27773261/156722949-4a32493c-ffd0-4b46-9595-fc053bdafd73.png)

**Comment by MengHao666** [comment]
@maitetsu

**Comment by sunhaha123** [comment]
![image](https://user-images.githubusercontent.com/27773261/156724297-221e08e6-faa6-4e4e-a3a1-ace2f3f9f8ec.png)
我在配置文件中看到这个，是不是反向动力学得到的rotation_matrix与MANO的排序不同？
![image](https://user-images.githubusercontent.com/27773261/156724553-29d082f2-227a-4e1a-9a22-e199d636e3e9.png)

**Comment by sunhaha123** [comment]
![image](https://user-images.githubusercontent.com/27773261/156727051-5b385502-bdb0-4f5d-920a-f83713dd8130.png)
![image](https://user-images.githubusercontent.com/27773261/156727180-1d7e614a-be63-4894-8e0f-2407509117f2.png)
拇指的顺序好像是有些问题

**Comment by MengHao666** [comment]
As I could remember, `ID2ROT` is to align the order of ration matrix to MANO fashion. I am busy with another project now, might @maitetsu could help.

**Comment by sunhaha123** [comment]
> As I could remember, `ID2ROT` is to align the order of ration matrix to MANO fashion. I am busy with another project now, might @maitetsu could help.

Thanks！ I find the vertexs matipulate the view_mat([[1.0, 0.0, 0.0],
                                                                                       [0.0, -1.0, 0],
                                                                                       [0.0, 0, -1.0]]),  so I really want to the konw the coordinate of rotation_matrix genertated by "AIK.adaptive_IK(). I directly use the rotation_matrix in blender ，it can't work well. The coordinate of 3d model of  in blender is Right hand coordinate system，and  the 3d model can be drived by smpl's outputs.
![image](https://user-images.githubusercontent.com/27773261/156733268-b2b479e3-0085-4755-bf4c-3f15199586c3.png)

**Comment by sunhaha123** [comment]
Thanks！ I find the vertexs matipulate the view_mat([[1.0, 0.0, 0.0],[0.0, -1.0, 0],[0.0, 0, -1.0]]), so I really want to the konw the coordinate of rotation_matrix genertated by "AIK.adaptive_IK(). I directly use the rotation_matrix in blender, it can't work well. The coordinate of 3d model  in blender is Right hand coordinate system，and the 3d model can be drived by smpl's outputs.
![image](https://user-images.githubusercontent.com/27773261/156733488-4668ef9d-3c86-4e20-9e0f-8ed65b7b6f0c.png)

**Comment by MengHao666** [comment]
> Thanks！ I find the vertexs matipulate the view_mat([[1.0, 0.0, 0.0],[0.0, -1.0, 0],[0.0, 0, -1.0]]), so I really want to the konw the coordinate of rotation_matrix genertated by "AIK.adaptive_IK(). I directly use the rotation_matrix in blender, it can't work well. The coordinate of 3d model in blender is Right hand coordinate system，and the 3d model can be drived by smpl's outputs. ![image](https://user-images.githubusercontent.com/27773261/156733488-4668ef9d-3c86-4e20-9e0f-8ed65b7b6f0c.png)

I would check it once I am free.

**Comment by MengHao666** [comment]
> > Thanks！ I find the vertexs matipulate the view_mat([[1.0, 0.0, 0.0],[0.0, -1.0, 0],[0.0, 0, -1.0]]), so I really want to the konw the coordinate of rotation_matrix genertated by "AIK.adaptive_IK(). I directly use the rotation_matrix in blender, it can't work well. The coordinate of 3d model in blender is Right hand coordinate system，and the 3d model can be drived by smpl's outputs. ![image](https://user-images.githubusercontent.com/27773261/156733488-4668ef9d-3c86-4e20-9e0f-8ed65b7b6f0c.png)
> 
> I would check it once I am free.

The rotation matrix of MANO might be different with yours.

**Comment by MengHao666** [comment]
sorry to say I don’t have free time to check it and I am not familiar with blender. The rotation matrix is actually based on manopth (the PyTorch implantation by hassony2).
