### ISSUE TITLE
关于原论文Mocap数据集

### ISSUE THREAD

**Issue by tonylin52** [MengHao666/Minimal-Hand-pytorch#59]
您好，我最近在阅读此论文，原论文描述利用Mocap数据集训练了IKNet部分，但是我一直未找到相关的数据集。

您这利用了新的办法去复现的IKNet。那么在复现IKNet的初期过程中，有没有遇到相似的数据集问题？

**Comment by MengHao666** [comment]
The offical project didn't provide such data for license reason. By the way, we didn't re-implement IKNet but use a mathematical solution.
