### ISSUE TITLE
Question about handutil.py

### ISSUE THREAD

**Issue by imabackstabber** [MengHao666/Minimal-Hand-pytorch#60]
Hi,I'm reading through the code,and I get a little confused by the function ``get_affine_transform_test`` and ``get_affine_trans_no_rot``,what's their utility?
Your reply is highly appreciated.

**Comment by MengHao666** [comment]
As I could remember, `get_affine_trans_no_rot` doesn't consider rotation when doing transformation. Could u find its usage in the specific train or test stage? Maybe you could know it clearly after that.

**Comment by imabackstabber** [comment]
thanks for your reply,I check the code invoke ``get_affine_transform_test``(in handataset.py),which get 2 return value:``affinetrans``, ``post_rot_trans``,but **only use** ``affinetrans`` to some groud truth like ``kp2d`` and ``clr``,while  ``post_rot_trans`` not used.
BTW, I read the reference link in readme,which redirect to a repo called [bihand](https://github.com/lixiny/bihand),in there handataset.py use ``post_rot_trans``,I also mentioned a same [issue](https://github.com/lixiny/bihand/issues/14) there.
Looking forward to your reply.

Best.

**Comment by MengHao666** [comment]
> Hi,I'm reading through the code,and I get a little confused by the function `get_affine_transform_test` and `get_affine_trans_no_rot`,what's their utility? Your reply is highly appreciated.

As you could see in [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/fa2c26480f3d168739aea4487362401f79cdd18f/datasets/handataset.py#L187), `get_affine_transform_test` is the to calculate transformation used when camrea parameters are not available and '`get_affine_transform' is  to calculate transformation used when camrea parameters are available.All the sp-called affine transformation is used to crop the image according to keypoint locations , mask , wanted size, augmentation setting, etc.

I am sorry I didn't matain this project well as I am busy with another project now.

**Comment by imabackstabber** [comment]
> > Hi,I'm reading through the code,and I get a little confused by the function `get_affine_transform_test` and `get_affine_trans_no_rot`,what's their utility? Your reply is highly appreciated.
> 
> As you could see in [here](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/fa2c26480f3d168739aea4487362401f79cdd18f/datasets/handataset.py#L187), `get_affine_transform_test` is the to calculate transformation used when camrea parameters are not available and '`get_affine_transform' is to calculate transformation used when camrea parameters are available.All the sp-called affine transformation is used to crop the image according to keypoint locations , mask , wanted size, augmentation setting, etc.
> 
> I am sorry I didn't matain this project well as I am busy with another project now.

OK,thanks for your reply,I'm clear about the utility of ``get_affine_transform_test `` and ``get_affine_trans_no_rot `` now! 😄 
However,I'm still wondering the **difference between the 2 return value**,``total_trans`` and ``affinetrans_post_rot``,of funciton ``get_affine_transform``.I notice they comes from ``origin_rot_center`` and ``transformed_center`` like:
```
def get_affine_transform(center, scale, optical_center, out_res, rot=0):
    rot_mat = np.zeros((3, 3))
    sn, cs = np.sin(rot), np.cos(rot)
    rot_mat[0, :2] = [cs, -sn]
    rot_mat[1, :2] = [sn, cs]
    rot_mat[2, 2] = 1
    # Rotate center to obtain coordinate of center in rotated image
    origin_rot_center = rot_mat.dot(center.tolist() + [1])[:2]
    # Get center for transform with verts rotated around optical axis
    # (through pixel center, smthg like 128, 128 in pixels and 0,0 in 3d world)
    # For this, rotate the center but around center of image (vs 0,0 in pixel space)
    t_mat = np.eye(3)
    t_mat[0, 2] = - optical_center[0]
    t_mat[1, 2] = - optical_center[1]
    t_inv = t_mat.copy()
    t_inv[:2, 2] *= -1
    transformed_center = (
        t_inv.dot(rot_mat).dot(t_mat).dot(center.tolist() + [1])
    )
    post_rot_trans = get_affine_trans_no_rot(origin_rot_center, scale, out_res)
    total_trans = post_rot_trans.dot(rot_mat)
    # check_t = get_affine_transform_bak(center, scale, res, rot)
    # print(total_trans, check_t)
    affinetrans_post_rot = get_affine_trans_no_rot(
        transformed_center[:2], scale, out_res
    )
    return (
        total_trans.astype(np.float32),
        affinetrans_post_rot.astype(np.float32),
    )
```
I understand ``transformed_center`` is position of hand center after ``translation->rotation->back translation`` ,in 
 the process,**it will rotate around optical center**(since translation will bring optical center to (0,0) ),and ``origin_rot_center`` is the **hand center rotate around (0,0)**,so what's the difference will they make?

**Comment by MengHao666** [comment]
It seems that only `total_trans` is used in this project as we need to consider the roatation during affine transformation.If you have interest, you could look detailed usage of  in 'affinetrans_post_rot' in [bihand](https://github.com/lixiny/bihand).

**Comment by imabackstabber** [comment]
OK,thanks!
