### ISSUE TITLE
i want to no why i cannot show the plot when running demo.py

### ISSUE THREAD

**Issue by hammerstone18** [MengHao666/Minimal-Hand-pytorch#61]
i want to no why i cannot show the plot when running demo.py

**Comment by hammerstone18** [comment]
![图片](https://user-images.githubusercontent.com/43516761/161429409-8a921e5e-7d6d-4f0f-9576-f71ab6536df7.png)

**Comment by hammerstone18** [comment]
the figure is only blank

**Comment by keristina** [comment]
Did you solve this problem, I had the same situation

**Comment by hammerstone18** [comment]
> Did you solve this problem, I had the same situation

i just install matplotlip and qt5 ，then itis OK

**Comment by hammerstone18** [comment]
> Did you solve this problem, I had the same situation

i just install matplotlip and qt5 ，then itis OK

**Comment by keristina** [comment]
> > Did you solve this problem, I had the same situation
> 
> i just install matplotlip and qt5 ，then itis OK

can i ask how to install qt5

**Comment by keristina** [comment]
> > Did you solve this problem, I had the same situation
> 
> i just install matplotlip and qt5 ，then itis OK

I solved the problem, thank you very much

**Comment by cgz6498** [comment]
![0d1db70ccd8dc7cb0cc8cf27a3496ce](https://github.com/MengHao666/Minimal-Hand-pytorch/assets/77420384/47662708-c9f7-4e09-ad9e-b41e2fc6ed49)
Excuse me, why is my effect so bad

**Comment by ohheysherry66** [comment]
> ![0d1db70ccd8dc7cb0cc8cf27a3496ce](https://private-user-images.githubusercontent.com/77420384/285123717-47662708-c9f7-4e09-ad9e-b41e2fc6ed49.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTU1MjYsIm5iZiI6MTcwMTQxNTIyNiwicGF0aCI6Ii83NzQyMDM4NC8yODUxMjM3MTctNDc2NjI3MDgtYzlmNy00ZTA5LWFkOWUtYjQxZTJmYzZlZDQ5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA3MjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTI1NTJlNDk4MWU2ZDM3NWE1YWVlNjkyMzVlMmY0NGY4OTBlNWFkYzFlYzNlMDgyMmViZTk3YmI3NGMyMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z1jDXLqYYG_wvDMR3wKVwZ9fDW8p8go92d46iXnTWEU) Excuse me, why is my effect so bad

The same situation counters to me. Have you solved it yet?
