### ISSUE TITLE
problem about showing 21 joints on the original image

### ISSUE THREAD

**Issue by bigbigbighead** [MengHao666/Minimal-Hand-pytorch#62]
Hi, I wanted to label the detected 21 joints on the original image but failed to get their coordinates. What's the meaning of uv parameters? They seems not to be the coordinates of the 21 joints on the orginal image.And how should I get them? Thanks in advance!

**Comment by MengHao666** [comment]
Note the `(u, v)` is the joint location on `32*32` heatmap with `128*128` input image, you may need to resize it for original image.
For more details, you can refer to [this](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/fa2c26480f3d168739aea4487362401f79cdd18f/datasets/handataset.py#L200) , [this](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/fa2c26480f3d168739aea4487362401f79cdd18f/model/detnet/detnet.py#L97) and  [this](https://github.com/MengHao666/Minimal-Hand-pytorch/blob/fa2c26480f3d168739aea4487362401f79cdd18f/datasets/handataset.py#L206).
