### ISSUE TITLE
about lamda_hm, lamda_dm, lamda_lm

### ISSUE THREAD

**Issue by ghost** [MengHao666/Minimal-Hand-pytorch#65]
why the loss weight lambd_hm/dm/lm is set so different? I mean most researcher set the ratio by 1:0.5:1

**Comment by MengHao666** [comment]
Hi，the original paper doesn't give specific configuration about the loss weights, and you can adjust them following your consideration. In this repo, I adjust them by their value. And could you point out who use the ratio by 1:0.5:1 ？I would be happy to check and learn.
