### ISSUE TITLE
关于得到的手部模型的形状不是很理想

### ISSUE THREAD

**Issue by ChaoYingYu** [MengHao666/Minimal-Hand-pytorch#67]
非常感谢您分享如此出色的成果。我在尝试通过一张图片生成一个手部模型。但我得到的手部模型的形状不太理想，我想请教下是否能够通过调节一些参数使它更接近真实手部的形状。
![image](https://user-images.githubusercontent.com/97202811/177089449-95584670-7d39-47b4-b9da-7fdadd5f576b.png)

**Comment by MengHao666** [comment]
the shape prediction actually depends on accurate hand pose prediction. however you can improve the normalization factor to make it close to mean shape，and vice verse.
