### ISSUE TITLE
About AIK output

### ISSUE THREAD

**Issue by Bruce-yu199** [MengHao666/Minimal-Hand-pytorch#71]
Hi, 
感谢你的工作，
请问你用的IK算法输出的是21个手指关节的旋转矩阵对嘛？，我现在已经用别的办法获取了手部21个关键点的3d坐标了，我在思考如何用你写的IK的方法来获得关节旋转信息以便后续驱动avatar等工作？还有一个问题是这种AIK算法实时性如何（大约需要多少ms）？

**Comment by MengHao666** [comment]
Thanks for interests!
AIK output joint rotation in MANO fashion, and the 21 joint here is also following with Mano's definition.
The whole pipleline, that is hand keypoint estimation plus AIK , could not achieve 60FPS as I rememebered.
However, you might use TensorRT or other ways to speed up the network inference. And you might also try to optimize and speed up the AIK procedure.
