### ISSUE TITLE
Pre-training datasets of the 4 models provided.

### ISSUE THREAD

**Issue by MickeyLLG** [MengHao666/Minimal-Hand-pytorch#76]
Which dataset is used for pre-training each of the 4 models that is provided in the link?

**Comment by MengHao666** [comment]
you could check the dataloader related code. As I remember, models are trained on mixed dataset and are selected as best for every single dataset

**Comment by MickeyLLG** [comment]
Thanks for the reply. Well, the "mixed" means CMU HandDB + Rendered Handpose Dataset + GANerated Hands Dataset, is that right?

**Comment by MengHao666** [comment]
yep, you could check my code.
