### ISSUE TITLE
about inference speed

### ISSUE THREAD

**Issue by EEWenbinWu** [MengHao666/Minimal-Hand-pytorch#8]
Can you tell me that you test on GPU or CPU? THX

**Comment by MengHao666** [comment]
Sorry, u can test by you own. I am busy with other issues.

**Comment by EEWenbinWu** [comment]
emmm, I mean that 0.27s/item in README is test on GPU or CPU.

**Comment by MengHao666** [comment]
let me see, GPU maybe. Actually, we will update later as using network to predict shape params. would be faster. It is also easy, and u may implement yourself.

**Comment by EEWenbinWu** [comment]
ok，thank you for your help.
